### ISSUE TITLE
Error on execute a "brew services start mongodb-community" command

### ISSUE THREAD

**Issue by RusselKL** [Homebrew/homebrew-services#607]
Apparently there is an outdated script for mongodb-community formula.  When you try to execute `brew services start mongodb-community@7.0` command this happens:
```
==> Tapping homebrew/services
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 2614, done.
remote: Counting objects: 100% (2614/2614), done.
remote: Compressing objects: 100% (1162/1162), done.
remote: Total 2614 (delta 1268), reused 2549 (delta 1258), pack-reused 0
Receiving objects: 100% (2614/2614), 682.52 KiB | 2.86 MiB/s, done.
Resolving deltas: 100% (1268/1268), done.
Tapped 1 command (45 files, 856.3KB).
Error: undefined method `plist_startup' for #<Formula mongodb-community (stable) /opt/homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community.rb>
Did you mean?  plist_name
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:71:in `service_startup?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:280:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:122:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:130:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```
As you see it tries to find some `plist_startup` method and gives an error. I temporarily resolved this by commented this line in formula_wrapper.rb file, but I guess its not a solution))

**Comment by SMillerDev** [comment]
The mongodb maintainers should update their formula. `plist_startup` has been removed from brew.

**Comment by tgfisher4** [comment]
Hi @SMillerDev! I'm happy to open an issue upstream, but can you clarify how the `mongodb-community` formulae need to be updated? Specifically, I am running into this issue with `mongodb-community@6.0`, but from what I can tell, [its formula](https://github.com/mongodb/homebrew-brew/blob/master/Formula/mongodb-community%406.0.rb) does not reference `plist_startup` at all.

Instead, the references to `plist_startup` I _can_ find are [in `homebrew-services` itself](https://github.com/Homebrew/homebrew-services/blob/6819359f72a8e0001370790685bf86c9897d9757/lib/service/formula_wrapper.rb#L71). In fact, from what I can tell, the error seems to be specifically caused by the _lack_ of a `plist_startup` in the `mongodb-community@6.0` formula:
```
Error: undefined method `plist_startup' for #<Formula mongodb-community@6.0 (stable) /opt/homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@6.0.rb>
```

If it helps color the issue at all, I am running into this issue after `brew update`ing to [4.2.0](https://brew.sh/2023/12/18/homebrew-4.2.0/): is it possible this is caused by differing behavior between [ruby 2.6 and ruby 3.1](https://github.com/Homebrew/brew/pull/16294/files#diff-fd5033f648c00cd452a042a918132b8c627b1e5f6a6211cc1b9c8830e87a1656R3-R4), or some other breaking change introduced in that update?

**Comment by dmoody256** [comment]
For those in this issue that may be interested the mongodb formula have been updated to work with homebrew 4.2.

**Comment by MikeMcQuaid** [comment]
Thanks @dmoody256!
